// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPJK44a79pzX1HJftstjHoRKRY3FrH9iA',
    appId: '1:641022325669:web:225954993a99aee1642e4c',
    messagingSenderId: '641022325669',
    projectId: 'zee-palm-apps',
    authDomain: 'zee-palm-apps.firebaseapp.com',
    storageBucket: 'zee-palm-apps.firebasestorage.app',
    measurementId: 'G-6Q51K3WPFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuxO7FsDBPZ4bnrRX4fCdqFNb4SsDrtg',
    appId: '1:641022325669:android:6578a17c84f87c08642e4c',
    messagingSenderId: '641022325669',
    projectId: 'zee-palm-apps',
    storageBucket: 'zee-palm-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Agdm9qeK_yF1DPnQwI_QnRqQR6Ul9oc',
    appId: '1:641022325669:ios:b2970bc4ce89f152642e4c',
    messagingSenderId: '641022325669',
    projectId: 'zee-palm-apps',
    storageBucket: 'zee-palm-apps.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Agdm9qeK_yF1DPnQwI_QnRqQR6Ul9oc',
    appId: '1:641022325669:ios:b2970bc4ce89f152642e4c',
    messagingSenderId: '641022325669',
    projectId: 'zee-palm-apps',
    storageBucket: 'zee-palm-apps.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPJK44a79pzX1HJftstjHoRKRY3FrH9iA',
    appId: '1:641022325669:web:c8dfba9d7ea8a3ef642e4c',
    messagingSenderId: '641022325669',
    projectId: 'zee-palm-apps',
    authDomain: 'zee-palm-apps.firebaseapp.com',
    storageBucket: 'zee-palm-apps.firebasestorage.app',
    measurementId: 'G-WX0FS8BW27',
  );
}
